language: php
php:
    - '7.4.0'
    - '8.0.0'

install:
    - composer install --dev
script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist
after_success:
    - travis_retry php vendor/bin/php-coveralls
